// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package store

import (
	"context"
)

const listAgents = `-- name: ListAgents :many
SELECT name, model, prompt, updated_at FROM agents ORDER BY name ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]*Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.Name,
			&i.Model,
			&i.Prompt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgent = `-- name: UpsertAgent :one
INSERT INTO agents (name, model, prompt, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    model = excluded.model,
    prompt = excluded.prompt,
    updated_at = excluded.updated_at
RETURNING name, model, prompt, updated_at
`

type UpsertAgentParams struct {
	Name      string
	Model     string
	Prompt    string
	UpdatedAt string
}

func (q *Queries) UpsertAgent(ctx context.Context, arg UpsertAgentParams) (*Agent, error) {
	row := q.db.QueryRowContext(ctx, upsertAgent,
		arg.Name,
		arg.Model,
		arg.Prompt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.Name,
		&i.Model,
		&i.Prompt,
		&i.UpdatedAt,
	)
	return &i, err
}
