// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package store

import (
	"context"
)

const getJobRun = `-- name: GetJobRun :one
SELECT name, last_run_at, duration_ms, status, detail FROM job_runs WHERE name = ?
`

func (q *Queries) GetJobRun(ctx context.Context, name string) (*JobRun, error) {
	row := q.db.QueryRowContext(ctx, getJobRun, name)
	var i JobRun
	err := row.Scan(
		&i.Name,
		&i.LastRunAt,
		&i.DurationMs,
		&i.Status,
		&i.Detail,
	)
	return &i, err
}

const listJobRuns = `-- name: ListJobRuns :many
SELECT name, last_run_at, duration_ms, status, detail FROM job_runs ORDER BY name ASC
`

func (q *Queries) ListJobRuns(ctx context.Context) ([]*JobRun, error) {
	rows, err := q.db.QueryContext(ctx, listJobRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.Name,
			&i.LastRunAt,
			&i.DurationMs,
			&i.Status,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobRun = `-- name: RecordJobRun :one
INSERT INTO job_runs (name, last_run_at, duration_ms, status, detail)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    last_run_at = excluded.last_run_at,
    duration_ms = excluded.duration_ms,
    status = excluded.status,
    detail = excluded.detail
RETURNING name, last_run_at, duration_ms, status, detail
`

type RecordJobRunParams struct {
	Name       string
	LastRunAt  string
	DurationMs int64
	Status     string
	Detail     string
}

func (q *Queries) RecordJobRun(ctx context.Context, arg RecordJobRunParams) (*JobRun, error) {
	row := q.db.QueryRowContext(ctx, recordJobRun,
		arg.Name,
		arg.LastRunAt,
		arg.DurationMs,
		arg.Status,
		arg.Detail,
	)
	var i JobRun
	err := row.Scan(
		&i.Name,
		&i.LastRunAt,
		&i.DurationMs,
		&i.Status,
		&i.Detail,
	)
	return &i, err
}
