// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Agent struct {
	Name      string
	Model     string
	Prompt    string
	UpdatedAt string
}

type Concern struct {
	ID        int64
	SessionID int64
	Agent     string
	File      string
	Line      sql.NullInt64
	Side      string
	Severity  string
	Title     string
	Body      string
	CreatedAt string
}

type PrReviewSession struct {
	ID                int64
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	Status            string
	Error             string
	DurationMs        int64
	CreatedAt         string
}

type Repo struct {
	ID      int64
	Owner   string
	Name    string
	AddedAt string
}

type ReviewAgent struct {
	ID                int64
	SessionID         int64
	Name              string
	Status            string
	Error             string
	Summary           string
	OpencodeSessionID string
	DurationMs        int64
	CreatedAt         string
}

type Theme struct {
	ID        int64
	Name      string
	UpdatedAt string
}

type TmuxSession struct {
	Owner     string
	Repo      string
	PrNumber  int64
	Name      string
	Worktree  string
	HeadSha   string
	Windows   int64
	CreatedAt string
}
