// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Concern struct {
	ID        int64
	SessionID int64
	Agent     string
	File      string
	Line      sql.NullInt64
	Side      string
	Severity  string
	Title     string
	Body      string
	CreatedAt string
}

type PrReviewSession struct {
	ID                int64
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	Agents            string
	Status            string
	Error             string
	DurationMs        int64
	CreatedAt         string
}

type Repo struct {
	ID      int64
	Owner   string
	Name    string
	AddedAt string
}
