// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opencode.sql

package store

import (
	"context"
)

const forgetOpencodeSession = `-- name: ForgetOpencodeSession :exec
DELETE FROM opencode_sessions WHERE session_id = ?
`

func (q *Queries) ForgetOpencodeSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, forgetOpencodeSession, sessionID)
	return err
}

const trackOpencodeSession = `-- name: TrackOpencodeSession :exec
INSERT INTO opencode_sessions (session_id, owner, repo, pr_number, agent, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(session_id) DO NOTHING
`

type TrackOpencodeSessionParams struct {
	SessionID string
	Owner     string
	Repo      string
	PrNumber  int64
	Agent     string
	CreatedAt string
}

func (q *Queries) TrackOpencodeSession(ctx context.Context, arg TrackOpencodeSessionParams) error {
	_, err := q.db.ExecContext(ctx, trackOpencodeSession,
		arg.SessionID,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.Agent,
		arg.CreatedAt,
	)
	return err
}

const unreachableOpencodeSessions = `-- name: UnreachableOpencodeSessions :many
SELECT session_id, owner, repo, pr_number, agent, created_at FROM opencode_sessions
WHERE session_id NOT IN (SELECT opencode_session_id FROM pr_review_sessions WHERE opencode_session_id <> '')
  AND session_id NOT IN (SELECT opencode_session_id FROM review_agents WHERE opencode_session_id <> '')
ORDER BY created_at ASC
`

func (q *Queries) UnreachableOpencodeSessions(ctx context.Context) ([]*OpencodeSession, error) {
	rows, err := q.db.QueryContext(ctx, unreachableOpencodeSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*OpencodeSession
	for rows.Next() {
		var i OpencodeSession
		if err := rows.Scan(
			&i.SessionID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Agent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
