// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr.sql

package store

import (
	"context"
)

const deletePRFiles = `-- name: DeletePRFiles :exec
DELETE FROM pr_files WHERE pr_id = ?
`

func (q *Queries) DeletePRFiles(ctx context.Context, prID int64) error {
	_, err := q.db.ExecContext(ctx, deletePRFiles, prID)
	return err
}

const getPR = `-- name: GetPR :one
SELECT id, owner, repo, number, title, body, state, author, html_url, draft, created_at, updated_at, synced_at FROM prs
WHERE owner = ? AND repo = ? AND number = ?
LIMIT 1
`

type GetPRParams struct {
	Owner  string
	Repo   string
	Number int64
}

func (q *Queries) GetPR(ctx context.Context, arg GetPRParams) (*Pr, error) {
	row := q.db.QueryRowContext(ctx, getPR, arg.Owner, arg.Repo, arg.Number)
	var i Pr
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
		&i.Author,
		&i.HtmlUrl,
		&i.Draft,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return &i, err
}

const insertPRFile = `-- name: InsertPRFile :one
INSERT INTO pr_files (pr_id, sha, filename, status, additions, deletions, changes, patch)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, pr_id, sha, filename, status, additions, deletions, changes, patch
`

type InsertPRFileParams struct {
	PrID      int64
	Sha       string
	Filename  string
	Status    string
	Additions int64
	Deletions int64
	Changes   int64
	Patch     string
}

func (q *Queries) InsertPRFile(ctx context.Context, arg InsertPRFileParams) (*PrFile, error) {
	row := q.db.QueryRowContext(ctx, insertPRFile,
		arg.PrID,
		arg.Sha,
		arg.Filename,
		arg.Status,
		arg.Additions,
		arg.Deletions,
		arg.Changes,
		arg.Patch,
	)
	var i PrFile
	err := row.Scan(
		&i.ID,
		&i.PrID,
		&i.Sha,
		&i.Filename,
		&i.Status,
		&i.Additions,
		&i.Deletions,
		&i.Changes,
		&i.Patch,
	)
	return &i, err
}

const listPRFiles = `-- name: ListPRFiles :many
SELECT id, pr_id, sha, filename, status, additions, deletions, changes, patch FROM pr_files
WHERE pr_id = ?
ORDER BY filename
`

func (q *Queries) ListPRFiles(ctx context.Context, prID int64) ([]*PrFile, error) {
	rows, err := q.db.QueryContext(ctx, listPRFiles, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PrFile
	for rows.Next() {
		var i PrFile
		if err := rows.Scan(
			&i.ID,
			&i.PrID,
			&i.Sha,
			&i.Filename,
			&i.Status,
			&i.Additions,
			&i.Deletions,
			&i.Changes,
			&i.Patch,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRs = `-- name: ListPRs :many
SELECT id, owner, repo, number, title, body, state, author, html_url, draft, created_at, updated_at, synced_at FROM prs
WHERE owner = ? AND repo = ?
ORDER BY updated_at DESC
`

type ListPRsParams struct {
	Owner string
	Repo  string
}

func (q *Queries) ListPRs(ctx context.Context, arg ListPRsParams) ([]*Pr, error) {
	rows, err := q.db.QueryContext(ctx, listPRs, arg.Owner, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Pr
	for rows.Next() {
		var i Pr
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.State,
			&i.Author,
			&i.HtmlUrl,
			&i.Draft,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPR = `-- name: UpsertPR :one
INSERT INTO prs (owner, repo, number, title, body, state, author, html_url, draft, created_at, updated_at, synced_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(owner, repo, number) DO UPDATE SET
    title      = excluded.title,
    body       = excluded.body,
    state      = excluded.state,
    draft      = excluded.draft,
    updated_at = excluded.updated_at,
    synced_at  = excluded.synced_at
RETURNING id, owner, repo, number, title, body, state, author, html_url, draft, created_at, updated_at, synced_at
`

type UpsertPRParams struct {
	Owner     string
	Repo      string
	Number    int64
	Title     string
	Body      string
	State     string
	Author    string
	HtmlUrl   string
	Draft     int64
	CreatedAt string
	UpdatedAt string
	SyncedAt  string
}

func (q *Queries) UpsertPR(ctx context.Context, arg UpsertPRParams) (*Pr, error) {
	row := q.db.QueryRowContext(ctx, upsertPR,
		arg.Owner,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.State,
		arg.Author,
		arg.HtmlUrl,
		arg.Draft,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SyncedAt,
	)
	var i Pr
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.State,
		&i.Author,
		&i.HtmlUrl,
		&i.Draft,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SyncedAt,
	)
	return &i, err
}
