// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_review.sql

package store

import (
	"context"
	"database/sql"
)

const createConcern = `-- name: CreateConcern :one
INSERT INTO concerns (session_id, file, line, side, severity, title, body, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, file, line, side, severity, title, body, created_at
`

type CreateConcernParams struct {
	SessionID int64
	File      string
	Line      sql.NullInt64
	Side      string
	Severity  string
	Title     string
	Body      string
	CreatedAt string
}

func (q *Queries) CreateConcern(ctx context.Context, arg CreateConcernParams) (*Concern, error) {
	row := q.db.QueryRowContext(ctx, createConcern,
		arg.SessionID,
		arg.File,
		arg.Line,
		arg.Side,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
	)
	var i Concern
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.File,
		&i.Line,
		&i.Side,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return &i, err
}

const createPRReviewSession = `-- name: CreatePRReviewSession :one
INSERT INTO pr_review_sessions (owner, repo, pr_number, head_sha, opencode_session_id, summary, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, owner, repo, pr_number, head_sha, opencode_session_id, summary, created_at
`

type CreatePRReviewSessionParams struct {
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	CreatedAt         string
}

func (q *Queries) CreatePRReviewSession(ctx context.Context, arg CreatePRReviewSessionParams) (*PrReviewSession, error) {
	row := q.db.QueryRowContext(ctx, createPRReviewSession,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.HeadSha,
		arg.OpencodeSessionID,
		arg.Summary,
		arg.CreatedAt,
	)
	var i PrReviewSession
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.HeadSha,
		&i.OpencodeSessionID,
		&i.Summary,
		&i.CreatedAt,
	)
	return &i, err
}

const getPRReviewSession = `-- name: GetPRReviewSession :one
SELECT id, owner, repo, pr_number, head_sha, opencode_session_id, summary, created_at FROM pr_review_sessions WHERE id = ?
`

func (q *Queries) GetPRReviewSession(ctx context.Context, id int64) (*PrReviewSession, error) {
	row := q.db.QueryRowContext(ctx, getPRReviewSession, id)
	var i PrReviewSession
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.HeadSha,
		&i.OpencodeSessionID,
		&i.Summary,
		&i.CreatedAt,
	)
	return &i, err
}

const listConcernsBySession = `-- name: ListConcernsBySession :many
SELECT id, session_id, file, line, side, severity, title, body, created_at FROM concerns WHERE session_id = ? ORDER BY id ASC
`

func (q *Queries) ListConcernsBySession(ctx context.Context, sessionID int64) ([]*Concern, error) {
	rows, err := q.db.QueryContext(ctx, listConcernsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Concern
	for rows.Next() {
		var i Concern
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.File,
			&i.Line,
			&i.Side,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRReviewSessionsByPR = `-- name: ListPRReviewSessionsByPR :many
SELECT id, owner, repo, pr_number, head_sha, opencode_session_id, summary, created_at FROM pr_review_sessions WHERE owner = ? AND repo = ? AND pr_number = ? ORDER BY created_at DESC
`

type ListPRReviewSessionsByPRParams struct {
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) ListPRReviewSessionsByPR(ctx context.Context, arg ListPRReviewSessionsByPRParams) ([]*PrReviewSession, error) {
	rows, err := q.db.QueryContext(ctx, listPRReviewSessionsByPR, arg.Owner, arg.Repo, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PrReviewSession
	for rows.Next() {
		var i PrReviewSession
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.HeadSha,
			&i.OpencodeSessionID,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
