// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pr_review.sql

package store

import (
	"context"
	"database/sql"
)

const createConcern = `-- name: CreateConcern :one
INSERT INTO concerns (session_id, agent, file, line, side, severity, title, body, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, agent, file, line, side, severity, title, body, created_at
`

type CreateConcernParams struct {
	SessionID int64
	Agent     string
	File      string
	Line      sql.NullInt64
	Side      string
	Severity  string
	Title     string
	Body      string
	CreatedAt string
}

func (q *Queries) CreateConcern(ctx context.Context, arg CreateConcernParams) (*Concern, error) {
	row := q.db.QueryRowContext(ctx, createConcern,
		arg.SessionID,
		arg.Agent,
		arg.File,
		arg.Line,
		arg.Side,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
	)
	var i Concern
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Agent,
		&i.File,
		&i.Line,
		&i.Side,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return &i, err
}

const createPRReviewSession = `-- name: CreatePRReviewSession :one
INSERT INTO pr_review_sessions (owner, repo, pr_number, head_sha, opencode_session_id, summary, agents, status, error, duration_ms, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, owner, repo, pr_number, head_sha, opencode_session_id, summary, agents, status, error, duration_ms, created_at
`

type CreatePRReviewSessionParams struct {
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	Agents            string
	Status            string
	Error             string
	DurationMs        int64
	CreatedAt         string
}

func (q *Queries) CreatePRReviewSession(ctx context.Context, arg CreatePRReviewSessionParams) (*PrReviewSession, error) {
	row := q.db.QueryRowContext(ctx, createPRReviewSession,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.HeadSha,
		arg.OpencodeSessionID,
		arg.Summary,
		arg.Agents,
		arg.Status,
		arg.Error,
		arg.DurationMs,
		arg.CreatedAt,
	)
	var i PrReviewSession
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.HeadSha,
		&i.OpencodeSessionID,
		&i.Summary,
		&i.Agents,
		&i.Status,
		&i.Error,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return &i, err
}

const getPRReviewSession = `-- name: GetPRReviewSession :one
SELECT id, owner, repo, pr_number, head_sha, opencode_session_id, summary, agents, status, error, duration_ms, created_at FROM pr_review_sessions WHERE id = ?
`

func (q *Queries) GetPRReviewSession(ctx context.Context, id int64) (*PrReviewSession, error) {
	row := q.db.QueryRowContext(ctx, getPRReviewSession, id)
	var i PrReviewSession
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.HeadSha,
		&i.OpencodeSessionID,
		&i.Summary,
		&i.Agents,
		&i.Status,
		&i.Error,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return &i, err
}

const listConcernsBySession = `-- name: ListConcernsBySession :many
SELECT id, session_id, agent, file, line, side, severity, title, body, created_at FROM concerns WHERE session_id = ? ORDER BY id ASC
`

func (q *Queries) ListConcernsBySession(ctx context.Context, sessionID int64) ([]*Concern, error) {
	rows, err := q.db.QueryContext(ctx, listConcernsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Concern
	for rows.Next() {
		var i Concern
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Agent,
			&i.File,
			&i.Line,
			&i.Side,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRReviewSessionsByPR = `-- name: ListPRReviewSessionsByPR :many
SELECT id, owner, repo, pr_number, head_sha, opencode_session_id, summary, agents, status, error, duration_ms, created_at FROM pr_review_sessions WHERE owner = ? AND repo = ? AND pr_number = ? ORDER BY created_at DESC
`

type ListPRReviewSessionsByPRParams struct {
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) ListPRReviewSessionsByPR(ctx context.Context, arg ListPRReviewSessionsByPRParams) ([]*PrReviewSession, error) {
	rows, err := q.db.QueryContext(ctx, listPRReviewSessionsByPR, arg.Owner, arg.Repo, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PrReviewSession
	for rows.Next() {
		var i PrReviewSession
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.HeadSha,
			&i.OpencodeSessionID,
			&i.Summary,
			&i.Agents,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPRReviewSessions = `-- name: ListRecentPRReviewSessions :many
SELECT
    s.id, s.owner, s.repo, s.pr_number, s.head_sha, s.opencode_session_id, s.summary, s.agents, s.status, s.error, s.duration_ms, s.created_at,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id) AS concern_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'high') AS high_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'medium') AS medium_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'low') AS low_count
FROM pr_review_sessions s
ORDER BY s.created_at DESC, s.id DESC
LIMIT ? OFFSET ?
`

type ListRecentPRReviewSessionsParams struct {
	Limit  int64
	Offset int64
}

type ListRecentPRReviewSessionsRow struct {
	ID                int64
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	Agents            string
	Status            string
	Error             string
	DurationMs        int64
	CreatedAt         string
	ConcernCount      int64
	HighCount         int64
	MediumCount       int64
	LowCount          int64
}

func (q *Queries) ListRecentPRReviewSessions(ctx context.Context, arg ListRecentPRReviewSessionsParams) ([]*ListRecentPRReviewSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPRReviewSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRecentPRReviewSessionsRow
	for rows.Next() {
		var i ListRecentPRReviewSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.HeadSha,
			&i.OpencodeSessionID,
			&i.Summary,
			&i.Agents,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
			&i.ConcernCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPRReviewSessionsByRepo = `-- name: ListRecentPRReviewSessionsByRepo :many
SELECT
    s.id, s.owner, s.repo, s.pr_number, s.head_sha, s.opencode_session_id, s.summary, s.agents, s.status, s.error, s.duration_ms, s.created_at,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id) AS concern_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'high') AS high_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'medium') AS medium_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'low') AS low_count
FROM pr_review_sessions s
WHERE s.owner = ? AND s.repo = ?
ORDER BY s.created_at DESC, s.id DESC
LIMIT ? OFFSET ?
`

type ListRecentPRReviewSessionsByRepoParams struct {
	Owner  string
	Repo   string
	Limit  int64
	Offset int64
}

type ListRecentPRReviewSessionsByRepoRow struct {
	ID                int64
	Owner             string
	Repo              string
	PrNumber          int64
	HeadSha           string
	OpencodeSessionID string
	Summary           string
	Agents            string
	Status            string
	Error             string
	DurationMs        int64
	CreatedAt         string
	ConcernCount      int64
	HighCount         int64
	MediumCount       int64
	LowCount          int64
}

func (q *Queries) ListRecentPRReviewSessionsByRepo(ctx context.Context, arg ListRecentPRReviewSessionsByRepoParams) ([]*ListRecentPRReviewSessionsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPRReviewSessionsByRepo,
		arg.Owner,
		arg.Repo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRecentPRReviewSessionsByRepoRow
	for rows.Next() {
		var i ListRecentPRReviewSessionsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.HeadSha,
			&i.OpencodeSessionID,
			&i.Summary,
			&i.Agents,
			&i.Status,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
			&i.ConcernCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoReviewSummary = `-- name: ListRepoReviewSummary :many
SELECT
    s.pr_number,
    s.status,
    s.created_at,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id) AS concern_count,
    (SELECT COUNT(*) FROM concerns c WHERE c.session_id = s.id AND c.severity = 'high') AS high_count
FROM pr_review_sessions s
WHERE s.owner = ? AND s.repo = ?
  AND s.id = (
      SELECT s2.id FROM pr_review_sessions s2
      WHERE s2.owner = s.owner AND s2.repo = s.repo AND s2.pr_number = s.pr_number
      ORDER BY s2.created_at DESC, s2.id DESC
      LIMIT 1
  )
`

type ListRepoReviewSummaryParams struct {
	Owner string
	Repo  string
}

type ListRepoReviewSummaryRow struct {
	PrNumber     int64
	Status       string
	CreatedAt    string
	ConcernCount int64
	HighCount    int64
}

func (q *Queries) ListRepoReviewSummary(ctx context.Context, arg ListRepoReviewSummaryParams) ([]*ListRepoReviewSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepoReviewSummary, arg.Owner, arg.Repo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRepoReviewSummaryRow
	for rows.Next() {
		var i ListRepoReviewSummaryRow
		if err := rows.Scan(
			&i.PrNumber,
			&i.Status,
			&i.CreatedAt,
			&i.ConcernCount,
			&i.HighCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
