// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recent_pr_filter.sql

package store

import (
	"context"
)

const getRecentPRFilter = `-- name: GetRecentPRFilter :one
SELECT value FROM recent_pr_filter WHERE id = 1
`

func (q *Queries) GetRecentPRFilter(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getRecentPRFilter)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setRecentPRFilter = `-- name: SetRecentPRFilter :exec
INSERT INTO recent_pr_filter (id, value, updated_at)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type SetRecentPRFilterParams struct {
	Value     string
	UpdatedAt string
}

func (q *Queries) SetRecentPRFilter(ctx context.Context, arg SetRecentPRFilterParams) error {
	_, err := q.db.ExecContext(ctx, setRecentPRFilter, arg.Value, arg.UpdatedAt)
	return err
}
