// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo.sql

package store

import (
	"context"
)

const addRepo = `-- name: AddRepo :one
INSERT INTO repos (owner, name, added_at)
VALUES (?, ?, ?)
ON CONFLICT(owner, name) DO UPDATE SET added_at = excluded.added_at
RETURNING id, owner, name, added_at
`

type AddRepoParams struct {
	Owner   string
	Name    string
	AddedAt string
}

func (q *Queries) AddRepo(ctx context.Context, arg AddRepoParams) (*Repo, error) {
	row := q.db.QueryRowContext(ctx, addRepo, arg.Owner, arg.Name, arg.AddedAt)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.AddedAt,
	)
	return &i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE owner = ? AND name = ?
`

type DeleteRepoParams struct {
	Owner string
	Name  string
}

func (q *Queries) DeleteRepo(ctx context.Context, arg DeleteRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, arg.Owner, arg.Name)
	return err
}

const listRepos = `-- name: ListRepos :many
SELECT id, owner, name, added_at FROM repos ORDER BY added_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]*Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
