// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: theme.sql

package store

import (
	"context"
)

const getTheme = `-- name: GetTheme :one
SELECT name FROM theme WHERE id = 1
`

func (q *Queries) GetTheme(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getTheme)
	var name string
	err := row.Scan(&name)
	return name, err
}

const setTheme = `-- name: SetTheme :exec
INSERT INTO theme (id, name, updated_at)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    updated_at = excluded.updated_at
`

type SetThemeParams struct {
	Name      string
	UpdatedAt string
}

func (q *Queries) SetTheme(ctx context.Context, arg SetThemeParams) error {
	_, err := q.db.ExecContext(ctx, setTheme, arg.Name, arg.UpdatedAt)
	return err
}
