// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tmux.sql

package store

import (
	"context"
)

const deleteTmuxSession = `-- name: DeleteTmuxSession :exec
DELETE FROM tmux_sessions
WHERE owner = ? AND repo = ? AND pr_number = ?
`

type DeleteTmuxSessionParams struct {
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) DeleteTmuxSession(ctx context.Context, arg DeleteTmuxSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteTmuxSession, arg.Owner, arg.Repo, arg.PrNumber)
	return err
}

const getTmuxSession = `-- name: GetTmuxSession :one
SELECT owner, repo, pr_number, name, worktree, head_sha, windows, created_at FROM tmux_sessions
WHERE owner = ? AND repo = ? AND pr_number = ?
`

type GetTmuxSessionParams struct {
	Owner    string
	Repo     string
	PrNumber int64
}

func (q *Queries) GetTmuxSession(ctx context.Context, arg GetTmuxSessionParams) (*TmuxSession, error) {
	row := q.db.QueryRowContext(ctx, getTmuxSession, arg.Owner, arg.Repo, arg.PrNumber)
	var i TmuxSession
	err := row.Scan(
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.Name,
		&i.Worktree,
		&i.HeadSha,
		&i.Windows,
		&i.CreatedAt,
	)
	return &i, err
}

const listTmuxSessions = `-- name: ListTmuxSessions :many
SELECT owner, repo, pr_number, name, worktree, head_sha, windows, created_at FROM tmux_sessions ORDER BY created_at DESC
`

func (q *Queries) ListTmuxSessions(ctx context.Context) ([]*TmuxSession, error) {
	rows, err := q.db.QueryContext(ctx, listTmuxSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TmuxSession
	for rows.Next() {
		var i TmuxSession
		if err := rows.Scan(
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.Name,
			&i.Worktree,
			&i.HeadSha,
			&i.Windows,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTmuxSession = `-- name: UpsertTmuxSession :one
INSERT INTO tmux_sessions (owner, repo, pr_number, name, worktree, head_sha, windows, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(owner, repo, pr_number) DO UPDATE SET
    name = excluded.name,
    worktree = excluded.worktree,
    head_sha = excluded.head_sha,
    windows = excluded.windows,
    created_at = excluded.created_at
RETURNING owner, repo, pr_number, name, worktree, head_sha, windows, created_at
`

type UpsertTmuxSessionParams struct {
	Owner     string
	Repo      string
	PrNumber  int64
	Name      string
	Worktree  string
	HeadSha   string
	Windows   int64
	CreatedAt string
}

func (q *Queries) UpsertTmuxSession(ctx context.Context, arg UpsertTmuxSessionParams) (*TmuxSession, error) {
	row := q.db.QueryRowContext(ctx, upsertTmuxSession,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.Name,
		arg.Worktree,
		arg.HeadSha,
		arg.Windows,
		arg.CreatedAt,
	)
	var i TmuxSession
	err := row.Scan(
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.Name,
		&i.Worktree,
		&i.HeadSha,
		&i.Windows,
		&i.CreatedAt,
	)
	return &i, err
}
